export const courseGroups = {
  "Engineering & Robotics": [
    "Concept Review",
    "Homework Help",
    "Lab Report Support",
    "Design Project Planning",
    "Prototype Building",
    "Code and Hardware Debugging",
    "Test Prep",
    "Presentation Prep",
  ],
  "Electronics & Embedded Systems": [
    "Concept Review",
    "Homework Help",
    "Circuit Troubleshooting",
    "Microcontroller Project Help",
    "Lab Report Support",
    "Simulation and Testing",
    "Build and Wiring Review",
    "Exam Prep",
  ],
  "Computer Science": [
    "Concept Review",
    "Homework Help",
    "Coding Assignment Help",
    "Debugging Support",
    "Project Planning",
    "Code Review",
    "Algorithm Practice",
    "Interview and Exam Prep",
  ],
  Mathematics: [
    "Concept Review",
    "Homework Help",
    "Practice Problem Walkthrough",
    "Formula and Method Review",
    "Word Problem Strategy",
    "Quiz and Test Prep",
    "Error Analysis",
    "Study Plan Help",
  ],
  "Natural Sciences": [
    "Concept Review",
    "Homework Help",
    "Lab Report Support",
    "Data Analysis Help",
    "Experiment Planning",
    "Research Summary Help",
    "Quiz and Test Prep",
    "Presentation Prep",
  ],
  "Humanities & Social Sciences": [
    "Concept Review",
    "Homework Help",
    "Reading Comprehension Support",
    "Essay Planning",
    "Source Analysis",
    "Argument and Debate Practice",
    "Quiz and Test Prep",
    "Presentation Prep",
  ],
  "Languages & Writing": [
    "Writing Feedback",
    "Essay Structure Help",
    "Grammar and Clarity Review",
    "Reading Comprehension Support",
    "Vocabulary Practice",
    "Speaking Practice",
    "Presentation and Speech Prep",
    "Research and Citation Help",
  ],
  "Arts, Design & Media": [
    "Creative Concept Development",
    "Project Feedback",
    "Portfolio Review",
    "Technique and Skill Practice",
    "Design Critique",
    "Editing and Refinement",
    "Presentation and Showcase Prep",
    "Collaboration Session",
  ],
} as const;

export type CourseCategory = keyof typeof courseGroups;
export type Course = (typeof courseGroups)[CourseCategory][number];
